# Generated by Django 5.0.2 on 2024-02-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default='dddd', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
